// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bfisvybfkpybmhbiabzk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmaXN2eWJma3B5Ym1oYmlhYnprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNzU2OTMsImV4cCI6MjA2NTY1MTY5M30.1YrjwOzEiscU9i_CNt4cqkJObzGqZfTI_PO0JxAHK4s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);